### ISSUE TITLE
[question] how to decrypt image file(s) that has RC4 encryption of the 0.0003 ratio of the file size

### ISSUE THREAD

**Issue by suphamster** [mauricelambert/RC4Encryption#1]
Problem is that file(s) partially encrypted with dynamic lengh of encrypted data depending on file size. Decryption key is 'ljSHSF%3@0'

**Comment by mauricelambert** [comment]
I don't understand the problem, you have encrypted a file after that you add data and after you try to decrypt the data ?

**Comment by mauricelambert** [comment]
You should use python to decrypt partially a file:

1. Open the file
2. Read only the encrypted data
3. Decrypt the encrypted data
4. Overwrite the encrypted data

And your file is decrypted.

**Comment by suphamster** [comment]
Problem is that I have thousands of partially encrypted files (it's some game wheree headers of image files is encrypted) but anyway it's probably my lack of python knowledge, not your tool problem since protection is more complicated than I thought.
